# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16j1Ik6iWcccu-B2WhAXTeLg5BwFWZlfP
"""

# -*- coding: utf-8 -*-
"""smart_bin_colab_v3.ipynb

# 🗑️ Smart Bin — YOLOv8 Training Pipeline (v3 — 5-Fold Cross-Validation)

Versi ini upgrade dari v2:

| Fitur baru | Manfaat |
|------------|---------|
| **Stratified 5-Fold Cross-Validation** | Estimasi performa jujur (mean ± std), tidak tergantung 1 split saja |
| **Setup lengkap + seed reproducible** | Hasil bisa diulang, cocok untuk laporan/skripsi |
| **Hyperparameter ditingkatkan** | cosine LR, warmup, label smoothing, close_mosaic, tuning bobot loss (box/cls/dfl) |
| **TTA saat validasi** | Akurasi validasi sedikit naik |
| **Output kaya** | Tabel per-fold, agregat mean±std, bar chart, heatmap per-class, kurva loss |
| **Final model** | Dilatih ulang di split 85/15 dengan epoch lebih banyak untuk deployment |
| **Export lengkap** | best.pt + ONNX + ZIP semua hasil |

---
⚠️ **Sebelum mulai:** Aktifkan GPU → `Runtime > Change runtime type > T4 GPU`

⏱️ **Estimasi waktu T4:** 5 fold × ~60 epoch ≈ 1–1.5 jam + final model ~20–30 menit.
Kalau cuma mau cek pipeline jalan, set `FOLDS_TO_RUN = 1` dan `EPOCHS_PER_FOLD = 10` dulu.

## 📦 Step 1 — Install Dependencies
"""

!pip install -q ultralytics roboflow scikit-learn pandas pyyaml seaborn matplotlib

import torch, platform, random, os
import numpy as np

print(f"PyTorch     : {torch.__version__}")
print(f"Python      : {platform.python_version()}")
print(f"CUDA avail  : {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU name    : {torch.cuda.get_device_name(0)}")
    print(f"GPU memory  : {torch.cuda.get_device_properties(0).total_memory/1e9:.1f} GB")
else:
    print("\n⚠️  GPU belum aktif!")
    print("   Runtime > Change runtime type > T4 GPU > Save")

# ── Reproducibility: kunci semua seed supaya hasil bisa diulang ──
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)
print(f"\n🔒 Semua seed dikunci ke {SEED} (hasil reproducible).")

"""## 🌐 Step 2 — Download Dataset dari Roboflow

> **Cara dapat Roboflow API Key (gratis):**
> 1. Daftar di [roboflow.com](https://roboflow.com)
> 2. Login → foto profil → **Settings** → tab **Roboflow API** → copy **Private API Key**
> 3. Tempel di `API_KEY` di bawah
"""

from roboflow import Roboflow

# ─────────────────────────────────────────
API_KEY = "7vCrksXsJMGmGCD8Q2y9"   # GANTI dengan API key kamu
# ─────────────────────────────────────────

if API_KEY in ("", "MASUKKAN_API_KEY_KAMU_DI_SINI"):
    raise ValueError("❌ Isi API_KEY dulu sebelum jalankan!")

rf = Roboflow(api_key=API_KEY)
project = rf.workspace("material-identification").project("garbage-classification-3")
dataset = project.version(2).download("yolov8", location="/content/smart_bin")

print("\n✅ Dataset berhasil didownload ke /content/smart_bin")

"""## 🔍 Step 3 — Cek Dataset & Baca data.yaml

Kita baca nama class dan struktur folder. Roboflow biasanya membagi dataset jadi
`train / valid / test` — untuk cross-validation nanti SEMUA gambar akan digabung
lalu dibagi ulang jadi 5 fold yang seimbang per-class.
"""

import glob, yaml
from pathlib import Path
from collections import Counter

DATASET_ROOT = Path("/content/smart_bin")

# Temukan data.yaml otomatis
yaml_files = glob.glob(str(DATASET_ROOT / "**/*.yaml"), recursive=True)
if not yaml_files:
    raise FileNotFoundError("❌ data.yaml tidak ditemukan! Pastikan download berhasil.")
DATA_YAML = yaml_files[0]
print(f"✅ data.yaml: {DATA_YAML}\n")

with open(DATA_YAML, encoding="utf8") as f:
    data_cfg = yaml.safe_load(f)

# names bisa berupa list ATAU dict tergantung versi export — tangani keduanya
raw_names = data_cfg.get("names")
if isinstance(raw_names, dict):
    CLASSES = {int(k): v for k, v in raw_names.items()}
else:
    CLASSES = {i: n for i, n in enumerate(raw_names)}
CLS_IDX = sorted(CLASSES.keys())
NUM_CLASSES = len(CLS_IDX)

print(f"📋 Jumlah class: {NUM_CLASSES}")
for i in CLS_IDX:
    print(f"   {i}: {CLASSES[i]}")

# Tampilkan struktur folder (1 level)
print("\n📁 Struktur folder:")
for sub in sorted(DATASET_ROOT.iterdir()):
    if sub.is_dir():
        imgs = list(sub.rglob("*.jpg")) + list(sub.rglob("*.png")) + list(sub.rglob("*.jpeg"))
        lbls = list(sub.rglob("*.txt"))
        print(f"   {sub.name}/  →  {len(imgs)} images, {len(lbls)} labels")

"""## 📊 Step 4 — Gabungkan Semua Split & Cek Distribusi Class

Karena kita pakai k-fold, kita kumpulkan semua gambar+label dari train/valid/test
ke satu kolam (pool). Lalu kita lihat distribusi class secara keseluruhan — kalau
ada class yang jumlahnya jauh lebih sedikit, itu kandidat utama untuk ditambah data.
"""

import shutil
import matplotlib.pyplot as plt
import seaborn as sns

POOL = Path("/content/smart_bin_pool")
(POOL / "images").mkdir(parents=True, exist_ok=True)
(POOL / "labels").mkdir(parents=True, exist_ok=True)

# Kumpulkan semua label & gambar dari seluruh dataset ke pool
all_labels = sorted(DATASET_ROOT.rglob("*labels/*.txt"))
all_images = []
for ext in ("*.jpg", "*.jpeg", "*.png"):
    all_images += list(DATASET_ROOT.rglob(f"*images/{ext}"))

img_by_stem = {p.stem: p for p in all_images}

copied = 0
for lbl in all_labels:
    img = img_by_stem.get(lbl.stem)
    if img is None:
        continue
    shutil.copy2(img, POOL / "images" / img.name)
    shutil.copy2(lbl, POOL / "labels" / lbl.name)
    copied += 1

print(f"✅ Pool dibuat: {copied} pasang gambar+label di {POOL}\n")

# Hitung distribusi class di seluruh pool
pool_labels = sorted((POOL / "labels").glob("*.txt"))
class_counter = Counter()
for lbl in pool_labels:
    with open(lbl) as f:
        for line in f:
            parts = line.split()
            if parts:
                class_counter[int(parts[0])] += 1

total_obj = sum(class_counter.values())
print(f"📊 Distribusi class (total {total_obj} objek dari {len(pool_labels)} gambar):")
print(f"  {'ID':<4}{'Class':<14}{'Count':>7}  Bar")
print("  " + "-" * 50)
max_c = max(class_counter.values()) if class_counter else 1
for cid in CLS_IDX:
    cnt = class_counter.get(cid, 0)
    bar = "█" * int(cnt / max_c * 25)
    pct = cnt / total_obj * 100 if total_obj else 0
    print(f"  {cid:<4}{CLASSES[cid]:<14}{cnt:>7}  {bar} ({pct:.1f}%)")

# Visual bar chart
plt.figure(figsize=(9, 4))
names = [CLASSES[c] for c in CLS_IDX]
counts = [class_counter.get(c, 0) for c in CLS_IDX]
sns.barplot(x=names, y=counts, hue=names, palette="viridis", legend=False)
plt.title("Distribusi Class — Seluruh Dataset")
plt.ylabel("Jumlah objek")
plt.xticks(rotation=30, ha="right")
for i, v in enumerate(counts):
    plt.text(i, v, str(v), ha="center", va="bottom", fontsize=9)
plt.tight_layout()
plt.show()

# Peringatan class tidak seimbang
if counts and min(counts) > 0 and max(counts) / min(counts) > 3:
    print("\n⚠️  Dataset tidak seimbang (rasio >3×). Class minoritas akan lebih sulit "
          "dideteksi — pertimbangkan tambah data untuk class tersebut.")

"""## 🔀 Step 5 — Buat Stratified 5-Fold Split

Mengikuti panduan resmi Ultralytics. Setiap gambar dijadikan "feature vector"
berisi jumlah objek per-class, lalu KFold membagi data jadi 5 bagian dengan
distribusi class yang dijaga semirip mungkin antar fold.
"""

import pandas as pd
from sklearn.model_selection import KFold
import datetime

KSPLIT = 5

# Feature vector: baris = gambar, kolom = class, nilai = jumlah objek
index = [lbl.stem for lbl in pool_labels]
labels_df = pd.DataFrame(0.0, index=index, columns=CLS_IDX)
for lbl in pool_labels:
    c = Counter()
    with open(lbl) as f:
        for line in f:
            parts = line.split()
            if parts:
                c[int(parts[0])] += 1
    for k, v in c.items():
        labels_df.loc[lbl.stem, k] = v

print(f"✅ Feature matrix: {labels_df.shape[0]} gambar × {labels_df.shape[1]} class\n")

kf = KFold(n_splits=KSPLIT, shuffle=True, random_state=SEED)
kfolds = list(kf.split(labels_df))

folds = [f"split_{n}" for n in range(1, KSPLIT + 1)]
folds_df = pd.DataFrame(index=index, columns=folds, dtype=object)
for i, (train_idx, val_idx) in enumerate(kfolds, start=1):
    folds_df.loc[labels_df.iloc[train_idx].index, f"split_{i}"] = "train"
    folds_df.loc[labels_df.iloc[val_idx].index, f"split_{i}"] = "val"

# Cek keseimbangan distribusi val/train per fold (idealnya rasio mirip antar split)
fold_distrb = pd.DataFrame(index=folds, columns=[CLASSES[c] for c in CLS_IDX], dtype=float)
for n, (tr, va) in enumerate(kfolds, start=1):
    tr_tot = labels_df.iloc[tr].sum()
    va_tot = labels_df.iloc[va].sum()
    ratio = va_tot / (tr_tot + 1e-7)
    fold_distrb.loc[f"split_{n}"] = ratio.values

print("📊 Rasio val/train per class tiap fold (idealnya mirip ~0.25):")
print(fold_distrb.round(3).to_string())

"""### Buat folder & data.yaml tiap fold, lalu salin file"""

from tqdm import tqdm

save_path = POOL / f"{datetime.date.today().isoformat()}_{KSPLIT}fold"
save_path.mkdir(parents=True, exist_ok=True)
ds_yamls = []

for split in folds:
    for sub in ("train", "val"):
        (save_path / split / sub / "images").mkdir(parents=True, exist_ok=True)
        (save_path / split / sub / "labels").mkdir(parents=True, exist_ok=True)
    yml = save_path / split / f"{split}.yaml"
    ds_yamls.append(yml)
    with open(yml, "w") as y:
        yaml.safe_dump({
            "path": str((save_path / split).as_posix()),
            "train": "train/images",
            "val": "val/images",
            "names": CLASSES,
        }, y, sort_keys=False)

# Salin gambar + label ke fold masing-masing (robust by stem)
pool_img_by_stem = {p.stem: p for p in (POOL / "images").glob("*")}
for lbl in tqdm(pool_labels, desc="Menyalin file ke fold"):
    img = pool_img_by_stem.get(lbl.stem)
    if img is None:
        continue
    for split in folds:
        role = folds_df.loc[lbl.stem, split]  # 'train' atau 'val'
        shutil.copy2(img, save_path / split / role / "images" / img.name)
        shutil.copy2(lbl, save_path / split / role / "labels" / lbl.name)

# Simpan catatan split (berguna untuk laporan)
folds_df.to_csv(save_path / "kfold_datasplit.csv")
fold_distrb.to_csv(save_path / "kfold_label_distribution.csv")
print(f"\n✅ {KSPLIT} fold siap di: {save_path}")
print("   Catatan split disimpan: kfold_datasplit.csv & kfold_label_distribution.csv")

"""## ⚙️ Step 6 — Konfigurasi Training

**Yang ditingkatkan dibanding v2 (terinspirasi paper garbage-classification & best practice Ultralytics):**

- `cos_lr=True` — learning rate turun mengikuti kurva cosine, konvergensi lebih halus
- `warmup_epochs` — pemanasan supaya training awal stabil
- `label_smoothing` — mengurangi overconfidence, sedikit menaikkan generalisasi
- `close_mosaic` — mematikan augmentasi mosaic di epoch-epoch terakhir → mAP final naik (trik standar)
- **Tuning bobot loss**: YOLOv8 menggabungkan 3 loss → `box` (CIoU, lokalisasi kotak), `cls` (BCE, klasifikasi), `dfl` (Distribution Focal Loss, presisi tepi kotak). Untuk dataset tidak seimbang, menaikkan `cls` sedikit bisa membantu.
"""

# ── KONFIGURASI UTAMA ──────────────────────────────
MODEL_WEIGHTS   = "yolov8n.pt"   # nano (cepat, edge). Ganti "yolov8s.pt" untuk akurasi lebih tinggi
EPOCHS_PER_FOLD = 60             # epoch per fold saat CV (estimasi performa)
FINAL_EPOCHS    = 120            # epoch untuk model final (deployment)
IMG_SIZE        = 640
BATCH_SIZE      = 32             # T4 muat 32; turunkan ke 16/8 kalau OOM
PATIENCE        = 15             # early stopping

FOLDS_TO_RUN    = KSPLIT         # set 1 untuk uji cepat, KSPLIT untuk CV penuh
RUN_FINAL_MODEL = True           # latih model final setelah CV

# Penanganan class imbalance (lihat Step 6b)
USE_CLASS_WEIGHTS = True         # True = aktifkan class-weighted loss untuk class minoritas
DAMPEN_WEIGHTS    = True         # True = redam bobot dgn sqrt (lebih aman, hindari false positive)
# ───────────────────────────────────────────────────

# Argumen training bersama (dipakai CV & final)
# Catatan: kalau USE_CLASS_WEIGHTS=True, 'cls' dikembalikan ke default 0.5
#          supaya tidak dobel dengan pembobotan per-class.
TRAIN_ARGS = dict(
    imgsz=IMG_SIZE,
    batch=BATCH_SIZE,
    patience=PATIENCE,

    # Optimizer & LR schedule
    optimizer="AdamW",
    lr0=0.001,
    lrf=0.01,
    cos_lr=True,
    warmup_epochs=5,
    weight_decay=0.0005,

    # Bobot komponen loss (CIoU + BCE + DFL)
    box=7.5,
    cls=0.5 if USE_CLASS_WEIGHTS else 0.6,   # 0.6 hanya kalau TIDAK pakai class weights
    dfl=1.5,

    # Regularisasi
    label_smoothing=0.05,

    # Augmentasi real-world
    hsv_h=0.015, hsv_s=0.7, hsv_v=0.4,
    degrees=10, translate=0.1, scale=0.5, shear=2.0,
    perspective=0.0005, flipud=0.0, fliplr=0.5,
    mosaic=1.0, mixup=0.1, copy_paste=0.1,
    close_mosaic=10,   # matikan mosaic 10 epoch terakhir

    device=0,
    seed=SEED,
    exist_ok=True,
    save=True,
    plots=True,
    verbose=False,
)
print("✅ Konfigurasi siap.")
print(f"   Model={MODEL_WEIGHTS} | {EPOCHS_PER_FOLD} epoch/fold × {FOLDS_TO_RUN} fold")

"""## ⚖️ Step 6b — Class-Weighted Loss (Penanganan Imbalance)

Kalau `USE_CLASS_WEIGHTS=True`, kita ganti BCE loss klasifikasi dengan versi
berbobot: class langka diberi bobot lebih besar (inverse-frequency) supaya model
menghukum kesalahan pada class minoritas lebih berat.

Bobot dihitung otomatis dari `class_counter` (hasil Step 4). Trainer kustom ini
**tetap memakai bobot pretrained** (COCO) — yang berubah hanya fungsi loss-nya.
Kalau `USE_CLASS_WEIGHTS=False`, training pakai trainer default biasa.
"""

TRAINER = None   # default: pakai trainer bawaan Ultralytics

if USE_CLASS_WEIGHTS:
    import torch
    from torch import nn
    from ultralytics.models.yolo.detect import DetectionTrainer
    from ultralytics.nn.tasks import DetectionModel
    from ultralytics.utils import RANK
    from ultralytics.utils.loss import v8DetectionLoss

    # Hitung bobot inverse-frequency dari distribusi class di pool (Step 4)
    _counts = np.array([class_counter.get(c, 0) for c in CLS_IDX], dtype=float)
    _counts[_counts == 0] = 1.0                 # hindari bagi nol
    _w = _counts.max() / _counts                # class langka -> bobot besar
    if DAMPEN_WEIGHTS:
        _w = np.sqrt(_w)                        # redam supaya tidak terlalu agresif
    _w = _w / _w.mean()                         # normalisasi (mean = 1.0)
    CLASS_WEIGHTS = torch.tensor(_w, dtype=torch.float32)

    print("⚖️  Class-weighted loss AKTIF. Bobot per class:")
    for c, x in zip(CLS_IDX, _w):
        print(f"   {CLASSES[c]:14s}: {x:.2f}")

    class WeightedLoss(v8DetectionLoss):
        """v8 detection loss dengan BCE berbobot per-class."""
        def __init__(self, model, class_weights=None):
            super().__init__(model)
            if class_weights is not None:
                self.bce = nn.BCEWithLogitsLoss(
                    pos_weight=class_weights.to(self.device), reduction="none")

    class WeightedModel(DetectionModel):
        def init_criterion(self):
            return WeightedLoss(self, class_weights=CLASS_WEIGHTS)

    class WeightedTrainer(DetectionTrainer):
        def get_model(self, cfg=None, weights=None, verbose=True):
            m = WeightedModel(cfg, nc=self.data["nc"], verbose=verbose and RANK == -1)
            if weights:
                m.load(weights)   # <- tetap muat bobot pretrained (COCO)
            return m

    TRAINER = WeightedTrainer
else:
    print("ℹ️  Class-weighted loss NONAKTIF (pakai cls=0.6 sebagai nudge ringan).")

# Helper: hanya kirim arg 'trainer' kalau memang dipakai
def train_kwargs():
    return {"trainer": TRAINER} if TRAINER is not None else {}

"""## 🚀 Step 7 — Training 5-Fold Cross-Validation

Tiap fold dilatih dari awal (model di-reset) lalu divalidasi pada bagian val fold itu.
Metrik tiap fold dikumpulkan untuk dirata-rata di Step 8.
"""

from ultralytics import YOLO
import gc

KFOLD_PROJECT = "/content/runs/kfold"
fold_results = []   # list of dict per fold

for k in range(FOLDS_TO_RUN):
    ds_yaml = ds_yamls[k]
    print("\n" + "=" * 55)
    print(f"  FOLD {k+1}/{FOLDS_TO_RUN}")
    print("=" * 55)

    model = YOLO(MODEL_WEIGHTS)   # reset model tiap fold (PENTING)
    model.train(data=str(ds_yaml), epochs=EPOCHS_PER_FOLD,
                project=KFOLD_PROJECT, name=f"fold_{k+1}",
                **train_kwargs(), **TRAIN_ARGS)

    # Validasi best.pt fold ini + TTA untuk ambil metrik & per-class
    best = Path(KFOLD_PROJECT) / f"fold_{k+1}" / "weights" / "best.pt"
    m = YOLO(str(best)).val(data=str(ds_yaml), augment=True, verbose=False,
                            project=KFOLD_PROJECT, name=f"fold_{k+1}_val")

    row = {
        "fold": k + 1,
        "mAP50": float(m.box.map50),
        "mAP50-95": float(m.box.map),
        "precision": float(m.box.mp),
        "recall": float(m.box.mr),
        "best_pt": str(best),
    }
    # per-class mAP50-95
    per_class = {}
    if hasattr(m.box, "maps"):
        for i, ap in enumerate(m.box.maps):
            per_class[CLASSES.get(i, str(i))] = float(ap)
    row["per_class"] = per_class
    fold_results.append(row)

    print(f"  ✅ Fold {k+1}: mAP50={row['mAP50']:.3f}  mAP50-95={row['mAP50-95']:.3f}  "
          f"P={row['precision']:.3f}  R={row['recall']:.3f}")

    del model
    gc.collect()
    torch.cuda.empty_cache()

print("\n🎉 Semua fold selesai!")

"""## 📈 Step 8 — Hasil Cross-Validation (mean ± std)

Inilah angka yang sebaiknya dilaporkan: bukan hasil satu split, tapi rata-rata
dan simpangan baku dari semua fold. Std kecil = model stabil/konsisten.
"""

import numpy as np
import pandas as pd

cv = pd.DataFrame([{k: r[k] for k in ("fold", "mAP50", "mAP50-95", "precision", "recall")}
                   for r in fold_results])
print("📋 Hasil per fold:")
print(cv.round(4).to_string(index=False))

print("\n" + "=" * 50)
print("  RINGKASAN CROSS-VALIDATION (mean ± std)")
print("=" * 50)
for col in ("mAP50", "mAP50-95", "precision", "recall"):
    mean, std = cv[col].mean(), cv[col].std()
    print(f"  {col:<11}: {mean:.3f} ± {std:.3f}")
print("=" * 50)

best_map = cv["mAP50"].mean()
if best_map >= 0.75:
    print("✅ Performa bagus & konsisten — siap dicoba real-world.")
elif best_map >= 0.60:
    print("⚠️  Lumayan. Tambah foto real dari tong kamu sebelum deploy.")
else:
    print("❌ Masih rendah. Cek distribusi class & tambah data.")

# Bar chart metrik per fold
fig, ax = plt.subplots(figsize=(10, 4))
x = np.arange(len(cv))
w = 0.2
for i, col in enumerate(("mAP50", "mAP50-95", "precision", "recall")):
    ax.bar(x + i * w, cv[col], w, label=col)
ax.set_xticks(x + 1.5 * w)
ax.set_xticklabels([f"Fold {f}" for f in cv["fold"]])
ax.set_ylim(0, 1)
ax.set_title("Metrik per Fold")
ax.legend(loc="lower right")
ax.grid(axis="y", alpha=0.3)
plt.tight_layout()
plt.show()

# Heatmap per-class mAP50-95 antar fold
pc = pd.DataFrame({f"Fold {r['fold']}": r["per_class"] for r in fold_results})
if not pc.empty:
    pc["mean"] = pc.mean(axis=1)
    plt.figure(figsize=(8, max(3, 0.5 * len(pc))))
    sns.heatmap(pc, annot=True, fmt=".2f", cmap="YlGnBu", vmin=0, vmax=1,
                cbar_kws={"label": "mAP50-95"})
    plt.title("Per-class mAP50-95 per Fold")
    plt.tight_layout()
    plt.show()

    print("\nClass paling lemah (rata-rata terendah) — kandidat tambah data:")
    print(pc["mean"].sort_values().head(3).round(3).to_string())

"""### Kurva loss & metrik training (fold terbaik)

Tiap fold menyimpan grafik training (box/cls/dfl loss, mAP, dll). Kita tampilkan
dari fold dengan mAP50 tertinggi.
"""

from IPython.display import Image, display

best_fold_idx = int(cv["mAP50"].idxmax())
best_fold_num = int(cv.loc[best_fold_idx, "fold"])
best_run = Path(KFOLD_PROJECT) / f"fold_{best_fold_num}"
print(f"📊 Menampilkan grafik dari Fold {best_fold_num} (mAP50 tertinggi)\n")

for title, fname in [
    ("📈 Loss & Metrik Training", "results.png"),
    ("🔢 Confusion Matrix", "confusion_matrix.png"),
    ("📉 PR Curve", "PR_curve.png"),
    ("📉 F1 Curve", "F1_curve.png"),
]:
    p = best_run / fname
    if p.exists():
        print(title)
        display(Image(str(p), width=720))

"""## 🏆 Step 9 — Latih Model Final untuk Deployment

CV bagus untuk *mengukur* performa, tapi untuk *dipakai* sebaiknya satu model
dilatih dengan lebih banyak data + epoch lebih panjang. Di sini kita buat split
stratified 85/15 dari seluruh pool, lalu latih model final.
"""

if RUN_FINAL_MODEL:
    from sklearn.model_selection import train_test_split

    final_dir = POOL / "final_split"
    for sub in ("train", "val"):
        (final_dir / sub / "images").mkdir(parents=True, exist_ok=True)
        (final_dir / sub / "labels").mkdir(parents=True, exist_ok=True)

    # split 85/15
    tr_stems, va_stems = train_test_split(index, test_size=0.15, random_state=SEED, shuffle=True)
    assign = {s: "train" for s in tr_stems}
    assign.update({s: "val" for s in va_stems})

    for lbl in tqdm(pool_labels, desc="Menyiapkan split final"):
        img = pool_img_by_stem.get(lbl.stem)
        if img is None:
            continue
        role = assign[lbl.stem]
        shutil.copy2(img, final_dir / role / "images" / img.name)
        shutil.copy2(lbl, final_dir / role / "labels" / lbl.name)

    final_yaml = final_dir / "final.yaml"
    with open(final_yaml, "w") as y:
        yaml.safe_dump({
            "path": str(final_dir.as_posix()),
            "train": "train/images",
            "val": "val/images",
            "names": CLASSES,
        }, y, sort_keys=False)

    print(f"\n✅ Split final: {len(tr_stems)} train / {len(va_stems)} val")
    print(f"🚀 Melatih model final ({FINAL_EPOCHS} epoch)...\n")

    final_model = YOLO(MODEL_WEIGHTS)
    final_model.train(data=str(final_yaml), epochs=FINAL_EPOCHS,
                      project="/content/runs", name="smart_bin_final",
                      **train_kwargs(), **TRAIN_ARGS)

    fm = final_model.val(data=str(final_yaml), augment=True, verbose=False)
    print("\n" + "=" * 45)
    print("  MODEL FINAL — HASIL VALIDASI")
    print("=" * 45)
    print(f"  mAP50      : {fm.box.map50:.3f}")
    print(f"  mAP50-95   : {fm.box.map:.3f}")
    print(f"  Precision  : {fm.box.mp:.3f}")
    print(f"  Recall     : {fm.box.mr:.3f}")
    print("=" * 45)
    if hasattr(fm.box, "maps"):
        print("\n  Per-class mAP50-95:")
        for i, ap in enumerate(fm.box.maps):
            name = CLASSES.get(i, str(i))
            flag = " ⚠ tambah data!" if ap < 0.60 else ""
            print(f"  {name:14s}: {ap:.3f}  {'█'*int(ap*25)}{flag}")

    FINAL_BEST = "/content/runs/smart_bin_final/weights/best.pt"
else:
    # kalau tidak melatih final, pakai best fold sebagai model deploy
    FINAL_BEST = fold_results[best_fold_idx]["best_pt"]
    print(f"ℹ️  RUN_FINAL_MODEL=False → pakai best.pt dari Fold {best_fold_num}: {FINAL_BEST}")

"""## 🖼️ Step 10 — Test Deteksi dengan Gambar Sendiri

Upload foto sampah dari kondisi real (dari tong kamu / webcam deployment).
"""

from google.colab import files
import glob

print("Upload 1+ foto untuk test (jpg/png):")
uploaded = files.upload()

if not uploaded:
    print("Tidak ada file diupload.")
else:
    model = YOLO(FINAL_BEST)
    test_dir = Path("/content/test_upload")
    test_dir.mkdir(exist_ok=True)
    for fname, data in uploaded.items():
        (test_dir / fname).write_bytes(data)

    results = model(str(test_dir), conf=0.50, save=True,
                    project="/content/runs", name="test_upload", exist_ok=True)

    print("\n🔍 Hasil deteksi:")
    for r in results:
        print(f"\n  📸 {Path(r.path).name}")
        if len(r.boxes) == 0:
            print("    ⚠️  Tidak ada objek (coba turunkan conf threshold)")
        for box in r.boxes:
            print(f"    → {model.names[int(box.cls[0])]:14s}  {float(box.conf[0]):.1%}")

    for img in glob.glob("/content/runs/test_upload/*.jpg") + glob.glob("/content/runs/test_upload/*.png"):
        display(Image(img, width=640))

"""## 💾 Step 11 — Export Model

`best.pt` untuk PyTorch, `.onnx` untuk deployment yang lebih portabel/cepat
(misalnya di Raspberry Pi atau runtime ONNX).
"""

from google.colab import files

best_model = Path(FINAL_BEST)
if best_model.exists():
    size_mb = best_model.stat().st_size / 1024 / 1024
    print(f"📦 best.pt: {size_mb:.1f} MB")

    # Export ONNX
    try:
        onnx_path = YOLO(str(best_model)).export(format="onnx", imgsz=IMG_SIZE)
        print(f"✅ ONNX: {onnx_path}")
    except Exception as e:
        print(f"⚠️  Export ONNX gagal: {e}")

    files.download(str(best_model))
    print("✅ best.pt didownload!")
else:
    print("⚠️  best.pt tidak ditemukan — pastikan training selesai.")

# ZIP semua hasil (CV + final + grafik) dalam satu file
print("\nMembuat ZIP semua hasil...")
shutil.make_archive("/content/smart_bin_results", "zip", "/content/runs")
files.download("/content/smart_bin_results.zip")
print("✅ ZIP didownload.")

"""## ➕ Bonus — Tambah Foto dari Tong Sendiri

**Langkah paling penting** untuk hasil real-world bagus:

1. Foto sampah langsung dari tong pakai webcam deployment
2. Annotate di [roboflow.com](https://roboflow.com), export ZIP format YOLOv8
3. Upload ZIP di cell bawah → otomatis digabung ke pool
4. Jalankan ulang dari **Step 5** (rebuild fold) lalu **Step 7** (training)
"""

from google.colab import files
import zipfile

print("Upload ZIP dataset dari Roboflow (format YOLOv8):")
uploaded = files.upload()

extract_dir = Path("/content/custom_data")
extract_dir.mkdir(exist_ok=True)
for filename in uploaded:
    if not filename.endswith(".zip"):
        print(f"⚠️  {filename} bukan ZIP, skip.")
        continue
    with zipfile.ZipFile(filename, "r") as z:
        z.extractall(str(extract_dir))
    print(f"✅ Diekstrak: {filename}")

# Gabungkan langsung ke POOL (bukan ke train Roboflow), beri prefix supaya tidak bentrok
add_img = add_lbl = 0
for lbl in extract_dir.rglob("*labels/*.txt"):
    stem = lbl.stem
    img = None
    for ext in (".jpg", ".jpeg", ".png"):
        cand = list(extract_dir.rglob(f"*images/{stem}{ext}"))
        if cand:
            img = cand[0]
            break
    if img is None:
        continue
    shutil.copy2(img, POOL / "images" / f"custom_{img.name}")
    shutil.copy2(lbl, POOL / "labels" / f"custom_{lbl.name}")
    add_img += 1
    add_lbl += 1

print(f"\n✅ Ditambahkan {add_img} gambar ke pool.")
print("🔁 Jalankan ulang dari Step 5 untuk rebuild fold + Step 7 untuk training.")

"""---

## 📋 Ringkasan Pipeline Deployment

```
Webcam (posisi final di tong)
        ↓
detect.py — load best.pt / model.onnx
        ↓
Filter confidence ≥ 0.65
        ↓
Ambil class dengan confidence tertinggi
        ↓
Kirim ke Arduino via Serial
        ↓
Servo sorting → slot yang tepat
```

### Troubleshooting

| Masalah | Solusi |
|---|---|
| OOM saat training | Turunkan `BATCH_SIZE` ke 16/8, atau `IMG_SIZE` ke 512 |
| CV terlalu lama | Set `FOLDS_TO_RUN=3` & `EPOCHS_PER_FOLD=40` |
| Std antar fold besar | Data kurang/imbalanced — tambah data class lemah |
| mAP rendah di 1 class | Lihat heatmap Step 8, tambah foto class itu, retrain |
| Akurasi mentok | Ganti `MODEL_WEIGHTS="yolov8s.pt"`, naikkan `FINAL_EPOCHS` |
| Lambat di Raspberry Pi | Pakai ONNX + `imgsz=320` saat inference |

### Catatan untuk laporan/skripsi
- Laporkan **mean ± std** dari Step 8, bukan angka satu split.
- Sertakan tabel per-fold + heatmap per-class sebagai bukti konsistensi.
- Sebut hyperparameter kunci: AdamW, cosine LR, close_mosaic, label smoothing,
  bobot loss box=7.5/cls=0.6/dfl=1.5.
"""

from google.colab import drive
drive.mount('/content/drive')

import shutil
from pathlib import Path

# Buat folder tujuan di Drive kamu
dest = Path('/content/drive/MyDrive/smart_bin')
dest.mkdir(parents=True, exist_ok=True)

# Copy best.pt model final
shutil.copy2('/content/runs/smart_bin_final/weights/best.pt', dest / 'best.pt')

# Copy juga ONNX kalau ada
onnx = Path('/content/runs/smart_bin_final/weights/best.onnx')
if onnx.exists():
    shutil.copy2(onnx, dest / 'best.onnx')

# Sekalian ZIP semua hasil (grafik, confusion matrix, dll)
shutil.copy2('/content/smart_bin_results.zip', dest / 'smart_bin_results.zip')

print('✅ Tersimpan di Google Drive → MyDrive/smart_bin/')

